apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudland.fullname" . }}-keys
  labels:
    {{- include "cloudland.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- toYaml .Values.keys | nindent 2 }}